name: CICD

on:
  push:
    branches: [main]

jobs:
  lint-build-deploy:
    name: Lint, build, and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install rust
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo test
      - run: wasm-pack test --headless --chrome
      - run: wasm-pack test --headless --firefox
      
      - name: Build wasm
        run: cd wasm && cargo install wasm-pack && wasm-pack build

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
